### ISSUE TITLE
Author key is used on article listing page instead of the author name

### ISSUE THREAD

**Issue by ryanwalls** [dencold/hasper#13]
My site is configured for multiple authors.  

e.g.
```
author:
  david:
    name: "David Hasselhoff"
    bio: "Don't Hassle the Hoff"
    location: "Baltimore, MD"
    thumbnail: "images/avatar.jpg"
  pamela:
    name: "Pamela Anderson"
    bio: "Little known fact, I am vegan"
    location: "Canada"
    thumbnail: "images/pamela.jpg"
```

On the home page with all the articles listed, the key for the author shows beside the date.  E.g. `david | 27 May 2016` instead of the full name `David Hasselhoff | 27 May 2016`
