### ISSUE TITLE
Example configuration has misnamed "shares" parameter

### ISSUE THREAD

**Issue by ryanwalls** [dencold/hasper#14]
Example config from README:
```
params:
  description: "David Hasselhoff loves telling you about Baywatch."
  cover: "images/cover.jpg"
  author: "david"
  logo: "images/logo.png"
  googleAnalyticsUserID: ""
  RSSLink: "http://feeds.feedburner.com/..."
  githubName: "thehoff"
  twitterName: "thehoff"
  hideHUGOSupport: false
  highlightjsTheme: "tomorrow-night-eighties"
  shares:
    twitter: false
    facebook: true
    google-plus: true
```

The actual parameter name for showing sharing options is "sharing".  See [share.html](layouts/partials/share.html).
